// <auto-generated />
using ERMAN;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERMAN.Migrations
{
    [DbContext(typeof(ErmanDbContext))]
    [Migration("20221120152614_studentPlacements2")]
    partial class studentPlacements2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERMAN.Models.FAQItem", b =>
                {
                    b.Property<int>("FAQItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FAQItemId"));

                    b.Property<string>("FAQAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FAQQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FAQItemId");

                    b.ToTable("FAQTable");
                });

            modelBuilder.Entity("ERMAN.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<string>("StudentEmailAddress")
                        .IsRequired()
                        .HasMaxLength(360)
                        .HasColumnType("character varying(360)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("StudentTable");
                });

            modelBuilder.Entity("ERMAN.Models.StudentPlacement", b =>
                {
                    b.Property<int>("PlacementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlacementId"));

                    b.Property<string>("DurationPrefered")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eng101")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eng102")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ErasmusApplicationWithGradesBehindSeUe")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsInWaitingList")
                        .HasColumnType("boolean");

                    b.Property<double>("LanguagePoints")
                        .HasColumnType("double precision");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalPoints")
                        .HasColumnType("double precision");

                    b.Property<double>("TranscriptGradeContribution")
                        .HasColumnType("double precision");

                    b.Property<double>("TranscriptGradeFromFour")
                        .HasColumnType("double precision");

                    b.Property<double>("TranscriptGradeFromHundred")
                        .HasColumnType("double precision");

                    b.Property<double>("TranscriptPoints")
                        .HasColumnType("double precision");

                    b.Property<double>("UECGPA")
                        .HasColumnType("double precision");

                    b.Property<int>("UESECount")
                        .HasColumnType("integer");

                    b.Property<string[]>("UniversityChoices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("PlacementId");

                    b.ToTable("StudentPlacements");
                });
#pragma warning restore 612, 618
        }
    }
}
